export type Category =
  | 'spices'
  | 'lentils'
  | 'rice'
  | 'flour'
  | 'snacks'
  | 'beverages'
  | 'pickles'
  | 'oils'
  | 'ready-to-eat'
  | 'namkeen'
  | 'fruits-veggies';

export interface Product {
  id: string;
  name: string;
  nameDE: string;
  description: string;
  descriptionDE: string;
  price: number;
  unit: string;
  category: Category;
  image: string;
  inStock: boolean;
  featured: boolean;
  brand: string;
}

const J = '/images/products/';
const SV = 'https://www.spicevillage.eu/cdn/shop/';
const PM = '/images/products/';

export const products: Product[] = [
  // ── RICE ──────────────────────────────────────────────────────────────────
  {
    id: 'p1',
    name: 'Basmati Rice Extra Long',
    nameDE: 'Basmati-Reis Extra Lang',
    description: 'Premium extra-long grain basmati rice, aged for perfect aroma and fluffy texture.',
    descriptionDE: 'Premium extra-langkörniger Basmatireis, gereift für perfektes Aroma.',
    price: 16.89,
    unit: '5 kg',
    category: 'rice',
    image: J + 'Daawat-5kg-Extra-Long-Basmatireis--extralange-Koerner--991193_1_63affdfe-8b20-4de5-a438-becb81668244.png',
    inStock: true,
    featured: true,
    brand: 'Daawat',
  },
  {
    id: 'p2',
    name: 'Sona Masoori Rice',
    nameDE: 'Sona Masoori Reis',
    description: 'Light, low-starch medium-grain rice from South India – ideal for everyday cooking.',
    descriptionDE: 'Leichter, stärkearmer mittelkörniger Reis aus Südindien.',
    price: 9.99,
    unit: '5 kg',
    category: 'rice',
    image: J + 'Anjappar-5kg-Kurnool-Sona-Masoori-Reis-9037835.png',
    inStock: true,
    featured: false,
    brand: 'Anjappar',
  },
  {
    id: 'p3',
    name: 'Superior Basmati Rice',
    nameDE: 'Superior Basmati-Reis',
    description: 'Long-grain basmati with a delicate fragrance, perfect for biryani and pilau.',
    descriptionDE: 'Langkörniger Basmati mit zartem Duft, ideal für Biryani.',
    price: 12.59,
    unit: '5 kg',
    category: 'rice',
    image: J + 'Heer-5kg-Superior-Basmati-Reis-extra-lang-991197_1.png',
    inStock: true,
    featured: false,
    brand: 'Heer',
  },
  {
    id: 'p4',
    name: 'Original Basmati Rice',
    nameDE: 'Original Basmati-Reis',
    description: 'Classic basmati rice with authentic aroma for daily use.',
    descriptionDE: 'Klassischer Basmatireis mit authentischem Aroma für den täglichen Gebrauch.',
    price: 4.19,
    unit: '1 kg',
    category: 'rice',
    image: J + 'Daawat-1kg-Original-Basmatireis-991187.png',
    inStock: true,
    featured: false,
    brand: 'Daawat',
  },

  // ── SPICES ────────────────────────────────────────────────────────────────
  {
    id: 'p5',
    name: 'Turmeric Powder (Haldi)',
    nameDE: 'Kurkumapulver (Haldi)',
    description: 'Pure ground turmeric with vibrant colour and warm earthy flavour.',
    descriptionDE: 'Reines gemahlenes Kurkuma mit lebhafter Farbe und erdiger Note.',
    price: 1.29,
    unit: '100 g',
    category: 'spices',
    image: J + 'Schani-100g-Kurkumapulver--Haldi--9016881.png',
    inStock: true,
    featured: true,
    brand: 'Schani',
  },
  {
    id: 'p6',
    name: 'Garam Masala Mix',
    nameDE: 'Garam Masala Gewürzmischung',
    description: 'Authentic blend of whole spices, freshly ground for rich, warming aroma.',
    descriptionDE: 'Authentische Mischung aus ganzen Gewürzen, frisch gemahlen.',
    price: 2.09,
    unit: '100 g',
    category: 'spices',
    image: J + 'TRS-100g-Garam-Masala-Mix-990629.png',
    inStock: true,
    featured: true,
    brand: 'TRS',
  },
  {
    id: 'p7',
    name: 'Cumin Seeds (Jeera)',
    nameDE: 'Kreuzkümmelsamen (Jeera)',
    description: 'Whole cumin seeds with warm, earthy and slightly bitter flavour.',
    descriptionDE: 'Ganze Kreuzkümmelsamen mit warmem, erdigen Geschmack.',
    price: 1.49,
    unit: '100 g',
    category: 'spices',
    image: J + 'Schani-100g-Kreuzkuemmelsamen--Jeera-Ganze--991693_ac68a55b-2a2d-4e64-bdbf-91b716521adc.png',
    inStock: true,
    featured: false,
    brand: 'Schani',
  },
  {
    id: 'p8',
    name: 'Kashmiri Mirch Chili Powder',
    nameDE: 'Kashmiri Mirch Chilipulver',
    description: 'Mild chili powder with deep red colour – perfect for vibrant curries.',
    descriptionDE: 'Mildes Chilipulver mit intensivem Rot – ideal für farbintensive Currys.',
    price: 2.29,
    unit: '100 g',
    category: 'spices',
    image: J + 'MDH-100g-Kashmiri-Mirch-Chillipulver-13011.png',
    inStock: true,
    featured: false,
    brand: 'MDH',
  },
  {
    id: 'p9',
    name: 'Coriander Powder (Dhaniya)',
    nameDE: 'Korianderpulver (Dhaniya)',
    description: 'Freshly ground coriander seeds with citrusy, slightly sweet flavour.',
    descriptionDE: 'Frisch gemahlene Koriandersamen mit zitrusartiger, leicht süßer Note.',
    price: 1.29,
    unit: '100 g',
    category: 'spices',
    image: J + 'Schani-100g-Korianderpulver--Dhaniya--991676_88f038e9-aab1-4bf1-838d-cab65d28100d.png',
    inStock: true,
    featured: false,
    brand: 'Schani',
  },
  {
    id: 'p10',
    name: 'Garam Masala',
    nameDE: 'Garam Masala',
    description: 'Premium blend of aromatic spices for rich, complex flavour in every dish.',
    descriptionDE: 'Premium-Mischung aromatischer Gewürze für reichen, komplexen Geschmack.',
    price: 2.49,
    unit: '100 g',
    category: 'spices',
    image: J + 'Everest-100g-Garam-Masala-9017228.png',
    inStock: true,
    featured: false,
    brand: 'Everest',
  },
  {
    id: 'p11',
    name: 'Green Cardamom (Elaichi)',
    nameDE: 'Grüner Kardamom (Elaichi)',
    description: 'Premium green cardamom pods with intense floral and sweet aroma.',
    descriptionDE: 'Premium grüne Kardamomkapseln mit intensivem Blumenduft.',
    price: 4.19,
    unit: '50 g',
    category: 'spices',
    image: J + 'TRS-50g-Gruener-Kardamom--Elaichi--990048_5b2b6587-a9bb-46fb-9b73-b5d5ff0edcac.png',
    inStock: true,
    featured: false,
    brand: 'TRS',
  },
  {
    id: 'p12',
    name: 'Chili Powder Extra Hot',
    nameDE: 'Chilipulver Extra Scharf',
    description: 'Fiery hot red chili powder for bold heat in curries and marinades.',
    descriptionDE: 'Feuriges rotes Chilipulver für intensive Schärfe in Currys.',
    price: 1.89,
    unit: '100 g',
    category: 'spices',
    image: J + 'TRS-100g-Chillipulver-Extrascharf-991002.png',
    inStock: true,
    featured: false,
    brand: 'TRS',
  },

  // ── LENTILS ───────────────────────────────────────────────────────────────
  {
    id: 'p13',
    name: 'Chana Dal (Split Chickpeas)',
    nameDE: 'Chana Dal (Kichererbsenlinsen)',
    description: 'Split Bengal gram – hearty lentil for dal, soups, and snacks.',
    descriptionDE: 'Gespaltene Bengalische Kichererbsen – ideal für Dal und Snacks.',
    price: 2.99,
    unit: '1 kg',
    category: 'lentils',
    image: J + 'Schani-1kg-Kichererbsen-halb-und-geschaelt--Chana-Dal--991557.png',
    inStock: true,
    featured: true,
    brand: 'Schani',
  },
  {
    id: 'p14',
    name: 'Masoor Dal (Red Lentils)',
    nameDE: 'Masoor Dal (Rote Linsen)',
    description: 'Split red lentils that cook quickly – great for soups and creamy dal.',
    descriptionDE: 'Gespaltene rote Linsen, ideal für Suppen und cremiges Dal.',
    price: 2.79,
    unit: '1 kg',
    category: 'lentils',
    image: J + 'Schani-1kg-Rote-Linsen--Masoor-Dal--991571_2f4f4a40-3619-4607-97fc-f387615c3e9e.png',
    inStock: true,
    featured: false,
    brand: 'Schani',
  },
  {
    id: 'p15',
    name: 'Toor Dal (Pigeon Peas)',
    nameDE: 'Toor Dal (Straucherbsen)',
    description: 'Yellow split pigeon peas – the classic base for South Indian sambar.',
    descriptionDE: 'Gelbe gespaltene Straucherbsen – die klassische Basis für Sambar.',
    price: 3.29,
    unit: '1 kg',
    category: 'lentils',
    image: J + 'Schani-1kg-Toor-Dal--Linsen--991586.png',
    inStock: true,
    featured: false,
    brand: 'Schani',
  },
  {
    id: 'p16',
    name: 'Moong Dal (Split Mung)',
    nameDE: 'Moong Dal (Mungbohnen)',
    description: 'Hulled split green mung beans – light, easy to digest, and nutritious.',
    descriptionDE: 'Enthülste gespaltene Mungbohnen – leicht, gut verdaulich und nahrhaft.',
    price: 3.39,
    unit: '1 kg',
    category: 'lentils',
    image: J + 'Schani-1kg-Halbe-geschaelte-Mungbohnen--Moong-Dal--991574_4fbb0ae6-b234-485c-a1fd-86262029e2f2.png',
    inStock: true,
    featured: false,
    brand: 'Schani',
  },
  {
    id: 'p17',
    name: 'Red Kidney Beans (Rajma)',
    nameDE: 'Rote Kidneybohnen (Rajma)',
    description: 'Firm red kidney beans – the heart of the beloved Punjabi rajma curry.',
    descriptionDE: 'Feste rote Kidneybohnen – das Herzstück des geliebten Punjabi-Currys.',
    price: 3.69,
    unit: '1 kg',
    category: 'lentils',
    image: J + 'Schani-1kg-Rote-Kidneybohnen--Rajma--991583.png',
    inStock: true,
    featured: false,
    brand: 'Schani',
  },
  {
    id: 'p18',
    name: 'Chickpeas (Kabuli Chana)',
    nameDE: 'Kichererbsen (Kabuli Chana)',
    description: 'Large white chickpeas for chole, hummus, and hearty stews.',
    descriptionDE: 'Große weiße Kichererbsen für Chole, Hummus und herzhafte Eintöpfe.',
    price: 2.99,
    unit: '1 kg',
    category: 'lentils',
    image: J + 'Schani-1kg-Kichererbsen--Kabuli-Chana--991559.png',
    inStock: true,
    featured: false,
    brand: 'Schani',
  },

  // ── FLOUR ─────────────────────────────────────────────────────────────────
  {
    id: 'p19',
    name: 'Chakki Atta Whole Wheat Flour',
    nameDE: 'Chakki Atta Vollkornmehl',
    description: 'Stone-ground whole wheat flour for soft, nutritious rotis and chapattis.',
    descriptionDE: 'Steingemähltes Vollkornmehl für weiche, nahrhafte Rotis und Chapattis.',
    price: 7.99,
    unit: '5 kg',
    category: 'flour',
    image: J + 'Aashirvaad-5kg--Exportpackung--Atta-Weizenmehl-21208.png',
    inStock: true,
    featured: true,
    brand: 'Aashirvaad',
  },
  {
    id: 'p20',
    name: 'Chakki Atta Whole Wheat Flour',
    nameDE: 'Chakki Atta Vollkornmehl',
    description: 'Family-size stone-ground whole wheat flour – great value for daily use.',
    descriptionDE: 'Familienpackung Vollkornmehl – bestes Preis-Leistungs-Verhältnis.',
    price: 15.79,
    unit: '10 kg',
    category: 'flour',
    image: J + 'Aashirvaad-10kg--Exportpackung--Atta-Weizenmehl-990554_abb25c00-4c9f-486d-9e8a-f06e18692362.png',
    inStock: true,
    featured: false,
    brand: 'Aashirvaad',
  },
  {
    id: 'p21',
    name: 'Pure Gram Flour (Besan)',
    nameDE: 'Reines Kichererbsenmehl (Besan)',
    description: 'Fine chickpea flour for pakoras, batter, sweets, and thickening sauces.',
    descriptionDE: 'Feines Kichererbsenmehl für Pakoras, Teig, Süßigkeiten und Saucen.',
    price: 3.29,
    unit: '1 kg',
    category: 'flour',
    image: J + 'Schani-1kg-Pure-Kichererbsenmehl--Besan--Mehl--991537_66a9fadc-3944-485b-a5dd-a97a526c6c17.png',
    inStock: true,
    featured: false,
    brand: 'Schani',
  },
  {
    id: 'p22',
    name: 'Chapati Atta White',
    nameDE: 'Chapati Atta Weiß',
    description: 'Smooth white chapati flour for light, thin flatbreads.',
    descriptionDE: 'Glattes weißes Chapati-Mehl für helle, dünne Fladenbrote.',
    price: 9.49,
    unit: '5 kg',
    category: 'flour',
    image: J + 'Schani-5kg-Chapati-Atta-Weiss-990477_37b010b5-fbba-4454-9386-d3eec53289e8.png',
    inStock: true,
    featured: false,
    brand: 'Schani',
  },
  {
    id: 'p23',
    name: 'Chakki Atta Whole Wheat',
    nameDE: 'Chakki Atta Vollkorn',
    description: 'Premium stone-ground whole wheat flour with natural bran for extra nutrition.',
    descriptionDE: 'Premium-Vollkornmehl mit natürlicher Kleie für extra Nährwert.',
    price: 9.79,
    unit: '5 kg',
    category: 'flour',
    image: J + 'Heer-5kg-Chakki-Atta--Vollkornmehl--990974.png',
    inStock: true,
    featured: false,
    brand: 'Heer',
  },

  // ── SNACKS ────────────────────────────────────────────────────────────────
  {
    id: 'p24',
    name: "Aloo Bhujia",
    nameDE: "Aloo Bhujia Snack",
    description: 'Crispy spiced potato sticks – the classic Indian tea-time snack.',
    descriptionDE: 'Knusprige gewürzte Kartoffelsticks – der klassische indische Snack.',
    price: 1.49,
    unit: '200 g',
    category: 'snacks',
    image: J + 'Haldiram-s-200g-Aloo-Bhujia--wuerzige-Kartoffelsticks--16251_1_5b0f5681-4eff-4792-8c83-774d323946bd.png',
    inStock: true,
    featured: true,
    brand: "Haldiram's",
  },
  {
    id: 'p25',
    name: 'Khatta Meetha Mix',
    nameDE: 'Khatta Meetha Mix',
    description: 'Sweet and sour chickpea mix – a popular Indian street food snack.',
    descriptionDE: 'Süß-saure Kichererbsenmischung – beliebter indischer Straßensnack.',
    price: 1.89,
    unit: '200 g',
    category: 'snacks',
    image: J + 'Haldiram-s-200g-Khatta-Meetha-Mix-aus-Kichererbsen-16267_1.png',
    inStock: true,
    featured: false,
    brand: "Haldiram's",
  },
  {
    id: 'p26',
    name: 'Parle-G Biscuits',
    nameDE: 'Parle-G Kekse',
    description: 'Iconic Indian glucose biscuits – loved by generations for their mild sweetness.',
    descriptionDE: 'Ikonische indische Glukosekekse – seit Generationen ein Klassiker.',
    price: 0.99,
    unit: '79.9 g',
    category: 'snacks',
    image: J + 'Parle-79-9g-Parle-G-Biscuits-9017280.png',
    inStock: true,
    featured: false,
    brand: 'Parle',
  },
  {
    id: 'p27',
    name: 'Kurkure Chili Chatka',
    nameDE: 'Kurkure Chili Chatka Snack',
    description: 'Crunchy corn puffs with a tangy chili seasoning – irresistibly moreish.',
    descriptionDE: 'Knusprige Maispuffs mit würzigem Chili-Gewürz – einfach unwiderstehlich.',
    price: 0.89,
    unit: '68 g',
    category: 'snacks',
    image: J + 'Kurkure-85g-Chilli-Chatka-Snack-9017146_1_66852864-7a12-4113-b978-da4b460d4506.png',
    inStock: true,
    featured: false,
    brand: 'Kurkure',
  },
  {
    id: 'p28',
    name: 'Bhujia Masala',
    nameDE: 'Bhujia Masala Snack',
    description: 'Spiced gram flour noodles – a classic namkeen snack full of flavour.',
    descriptionDE: 'Gewürzte Kichererbsenmehl-Nudeln – ein klassischer Namkeen-Snack.',
    price: 1.49,
    unit: '200 g',
    category: 'snacks',
    image: J + 'Haldiram-s-200g-Bhujia-Masala-16253_d5e0ab5f-4765-4fd2-a712-68fd82daac43.png',
    inStock: true,
    featured: false,
    brand: "Haldiram's",
  },

  // ── BEVERAGES ─────────────────────────────────────────────────────────────
  {
    id: 'p29',
    name: 'Rooh Afza Rose Syrup',
    nameDE: 'Rooh Afza Rosensirup',
    description: 'Iconic fragrant rose sherbet syrup – mix with water, milk, or yoghurt.',
    descriptionDE: 'Ikonischer duftender Rosensirup – mit Wasser, Milch oder Joghurt mischen.',
    price: 3.99,
    unit: '800 ml',
    category: 'beverages',
    image: J + 'Hamdard-800ml-Rooh-Afza-Sirup-990061_1.png',
    inStock: true,
    featured: true,
    brand: 'Hamdard',
  },
  {
    id: 'p30',
    name: 'Mango Juice Deluxe',
    nameDE: 'Mango Saft Deluxe',
    description: 'Rich and smooth mango juice made from the finest Indian Alphonso mangoes.',
    descriptionDE: 'Reichhaltiger, samtiger Mangosaft aus den besten indischen Alphonso-Mangos.',
    price: 3.69,
    unit: '1 L',
    category: 'beverages',
    image: J + 'Rubicon-1l-Mangosaft-Deluxe-990294.png',
    inStock: true,
    featured: false,
    brand: 'Rubicon',
  },
  {
    id: 'p31',
    name: 'Tea Gold',
    nameDE: 'Tee Gold',
    description: 'Strong, malty black tea – perfect for a robust Indian chai.',
    descriptionDE: 'Starker, malziger schwarzer Tee – ideal für einen kräftigen indischen Chai.',
    price: 7.19,
    unit: '450 g',
    category: 'beverages',
    image: J + 'TATA-450g-Tee-Gold-991180_1.png',
    inStock: true,
    featured: false,
    brand: 'TATA',
  },
  {
    id: 'p32',
    name: 'Masala Chai Tea',
    nameDE: 'Masala Chai Tee',
    description: 'Aromatic spiced tea blend with cardamom, ginger, and cinnamon.',
    descriptionDE: 'Aromatische Gewürztee-Mischung mit Kardamom, Ingwer und Zimt.',
    price: 5.09,
    unit: '250 g',
    category: 'beverages',
    image: J + 'Wagh-Bakri-250g-Masala-Tee--Dose--22025.png',
    inStock: true,
    featured: false,
    brand: 'Wagh Bakri',
  },

  // ── PICKLES ───────────────────────────────────────────────────────────────
  {
    id: 'p33',
    name: 'Mango Pickle in Oil',
    nameDE: 'Mango-Pickle in Öl',
    description: 'Traditional spicy raw mango pickle preserved in oil with whole spices.',
    descriptionDE: 'Traditionelles würziges Mango-Pickle in Öl mit ganzen Gewürzen.',
    price: 3.99,
    unit: '1 kg',
    category: 'pickles',
    image: 'https://www.jamoona.com/cdn/shop/files/Ahmed-1kg-Mango-Pickle-in-oel--extra-scharf--9040067.png?v=1753260979&width=500',
    inStock: true,
    featured: false,
    brand: 'Ahmed',
  },
  {
    id: 'p34',
    name: 'Mango Pickle (Mild)',
    nameDE: 'Mango-Pickle (Mild)',
    description: 'Gently spiced mango pickle for those who prefer a milder tang.',
    descriptionDE: 'Mild gewürztes Mango-Pickle für alle, die es weniger scharf mögen.',
    price: 3.69,
    unit: '283 g',
    category: 'pickles',
    image: J + 'Patak-s-283g-Mango-Pickles-mild--Eingelegte-Mango--13635_1.png',
    inStock: true,
    featured: false,
    brand: "Patak's",
  },
  {
    id: 'p35',
    name: 'Mixed Pickles',
    nameDE: 'Gemischte Pickles',
    description: 'A tangy medley of mixed vegetables pickled with Indian spices.',
    descriptionDE: 'Eine säuerliche Mischung aus verschiedenen Gemüsesorten mit indischen Gewürzen.',
    price: 4.09,
    unit: '1 kg',
    category: 'pickles',
    image: J + 'Ahmed-1kg-Gemischte-Pickles--13066_1.png',
    inStock: true,
    featured: false,
    brand: 'Ahmed',
  },
  {
    id: 'p36',
    name: 'Concentrated Tamarind Paste',
    nameDE: 'Konzentrierte Tamarindenpaste',
    description: 'Ready-to-use tamarind paste for chutneys, curries, and sauces.',
    descriptionDE: 'Gebrauchsfertige Tamarindenpaste für Chutneys, Currys und Saucen.',
    price: 4.39,
    unit: '400 g',
    category: 'pickles',
    image: J + 'TRS-400g-Konzentrierte-Tamarindenpaste-991746_1.png',
    inStock: true,
    featured: false,
    brand: 'TRS',
  },

  // ── MORE SNACKS (Spice Village + Jamoona) ────────────────────────────────
  {
    id: 'p41',
    name: 'Bhakarwadi',
    nameDE: 'Bhakarwadi Snack',
    description: 'Crispy spiced pinwheel snack from Maharashtra – sweet, savoury, and tangy.',
    descriptionDE: 'Knuspriger Bhakarwadi-Snack aus Maharashtra – süß, würzig und säuerlich.',
    price: 3.99,
    unit: '250 g',
    category: 'snacks',
    image: SV + 'files/chitale-indian-default-title-chitale-bhakarwadi-250gm-37168212902156.webp',
    inStock: true,
    featured: false,
    brand: 'Chitale',
  },
  {
    id: 'p42',
    name: 'Boondi Masala',
    nameDE: 'Boondi Masala',
    description: 'Tiny fried chickpea balls seasoned with masala – light and addictive.',
    descriptionDE: 'Kleine gebratene Kichererbsenbällchen mit Masala – leicht und unwiderstehlich.',
    price: 1.99,
    unit: '200 g',
    category: 'snacks',
    image: J + 'Haldiram-s-200g-Boondi-Masala-16256_1.png',
    inStock: true,
    featured: false,
    brand: "Haldiram's",
  },
  {
    id: 'p43',
    name: 'Samosa Snack',
    nameDE: 'Samosa Snack',
    description: 'Crunchy samosa-flavoured snack mix with chickpeas, cashews, and raisins.',
    descriptionDE: 'Knuspriger Samosa-Snack mit Kichererbsen, Cashews und Rosinen.',
    price: 2.09,
    unit: '200 g',
    category: 'snacks',
    image: J + 'Haldiram-s-200g-Samosa-Snack--mit-Kichererbsen--Cashews-und-Rosinen--16276_1.png',
    inStock: true,
    featured: false,
    brand: "Haldiram's",
  },

  // ── MORE BEVERAGES (Spice Village + Jamoona) ──────────────────────────────
  {
    id: 'p44',
    name: 'Badam Drink Powder',
    nameDE: 'Badam Getränkepulver',
    description: 'Rich almond-flavoured drink mix – warm or cold, a South Indian favourite.',
    descriptionDE: 'Reichhaltiges Mandel-Getränkepulver – warm oder kalt, ein Klassiker.',
    price: 3.29,
    unit: '200 g',
    category: 'beverages',
    image: SV + 'products/mtr-drink-mixes-default-title-mtr-badam-drink-powder-200gm-25644646957210.jpg',
    inStock: true,
    featured: false,
    brand: 'MTR',
  },
  {
    id: 'p45',
    name: 'Red Label Tea',
    nameDE: 'Red Label Tee',
    description: 'India\'s favourite full-bodied black tea – bold and refreshing every cup.',
    descriptionDE: 'Indiens beliebtester Schwarztee – kräftig und erfrischend bei jedem Aufguss.',
    price: 4.99,
    unit: '500 g',
    category: 'beverages',
    image: J + 'Brooke-Bond-500g-Red-Label-9039018.png',
    inStock: true,
    featured: false,
    brand: 'Brooke Bond',
  },
  {
    id: 'p46',
    name: 'Guava Juice',
    nameDE: 'Guaven-Saft',
    description: 'Sweet and tropical guava nectar – refreshing and full of flavour.',
    descriptionDE: 'Süßer tropischer Guaven-Nektar – erfrischend und geschmacksintensiv.',
    price: 3.69,
    unit: '1 L',
    category: 'beverages',
    image: J + 'Rubicon-1l-Guavensaft-17123.png',
    inStock: true,
    featured: false,
    brand: 'Rubicon',
  },
  {
    id: 'p47',
    name: 'Tea Gold',
    nameDE: 'Tea Gold',
    description: 'Premium large-pack Gold tea – consistent strength and golden colour.',
    descriptionDE: 'Premium Großpackung Gold-Tee – gleichmäßige Stärke und goldene Farbe.',
    price: 16.99,
    unit: '900 g',
    category: 'beverages',
    image: SV + 'products/tata-tea-tea-coffee-default-title-tata-tea-gold-900gm-25644668059802.jpg',
    inStock: true,
    featured: false,
    brand: 'TATA',
  },

  // ── MORE PICKLES (Spice Village) ──────────────────────────────────────────
  {
    id: 'p48',
    name: 'Cut Mango Pickle',
    nameDE: 'Gehacktes Mango-Pickle',
    description: 'Chunky cut mango pickle with a bold, spicy marinade.',
    descriptionDE: 'Stückiges Mango-Pickle mit kräftiger, würziger Marinade.',
    price: 3.49,
    unit: '300 g',
    category: 'pickles',
    image: SV + 'products/priya-indian-default-title-priya-cut-mango-pickle-300gm-25644561105050.jpg',
    inStock: true,
    featured: false,
    brand: 'Priya',
  },
  {
    id: 'p49',
    name: 'Lime Pickle (Without Garlic)',
    nameDE: 'Limetten-Pickle (ohne Knoblauch)',
    description: 'Tangy lime pickle preserved in spiced oil – great with rice and dal.',
    descriptionDE: 'Säuerliches Limetten-Pickle in Gewürzöl – ideal zu Reis und Dal.',
    price: 3.49,
    unit: '300 g',
    category: 'pickles',
    image: SV + 'products/priya-indian-default-title-priya-lime-pickle-without-garlic-300gm-25644559466650.jpg',
    inStock: true,
    featured: false,
    brand: 'Priya',
  },

  // ── MORE RICE (large packs) ───────────────────────────────────────────────
  {
    id: 'p50',
    name: 'Sona Masoori Rice',
    nameDE: 'Sona Masoori Reis',
    description: 'Bulk pack of aromatic Sona Masoori – perfect for families.',
    descriptionDE: 'Großpackung aromatischer Sona Masoori – ideal für Familien.',
    price: 18.89,
    unit: '10 kg',
    category: 'rice',
    image: J + 'Anjappar-10kg-Kurnool-Sona-Masoori-9017057_1.png',
    inStock: true,
    featured: false,
    brand: 'Anjappar',
  },
  {
    id: 'p51',
    name: 'Original Basmati Rice',
    nameDE: 'Original Basmati-Reis',
    description: 'Economy family pack of original basmati – everyday quality at best value.',
    descriptionDE: 'Familienpackung Original-Basmati – beste Qualität zum günstigsten Preis.',
    price: 31.39,
    unit: '10 kg',
    category: 'rice',
    image: 'https://www.jamoona.com/cdn/shop/files/Daawat-10kg-Original-Basmatireis-991190_1_370e2d72-07c6-458e-8423-d726711c2c65.png?v=1753228441&width=500',
    inStock: true,
    featured: false,
    brand: 'Daawat',
  },

  // ── MORE LENTILS (bulk packs) ─────────────────────────────────────────────
  {
    id: 'p52',
    name: 'Chana Dal (Split Chickpeas)',
    nameDE: 'Chana Dal (Kichererbsenlinsen)',
    description: 'Value 2 kg pack of split chickpeas – stock up and save.',
    descriptionDE: '2-kg-Vorteilspackung gespaltener Kichererbsen – günstiger einkaufen.',
    price: 5.09,
    unit: '2 kg',
    category: 'lentils',
    image: J + 'Schani-2kg-Kichererbsen-halb-und-geschaelt--Chana-Dal--991558_091b02ea-d03d-49bd-84b3-aa36f7e4e80d.png',
    inStock: true,
    featured: false,
    brand: 'Schani',
  },

  // ── MORE OILS & GHEE ──────────────────────────────────────────────────────
  {
    id: 'p53',
    name: 'Butter Ghee',
    nameDE: 'Butter Ghee',
    description: 'Premium clarified butter ghee in 1 kg economy size.',
    descriptionDE: 'Premium-Butterschmalz in 1-kg-Vorteilsgröße.',
    price: 14.69,
    unit: '1 kg',
    category: 'oils',
    image: J + 'Khanum-1kg-Butter-Ghee-991714.png',
    inStock: true,
    featured: false,
    brand: 'Khanum',
  },

  // ── READY TO EAT (Patel Markt) ───────────────────────────────────────────
  {
    id: 'CS-001',
    name: 'Madhi Khamni',
    nameDE: 'Madhi Khamni',
    description: "Experience the authentic Sweet & Spicy taste of Surat with Madhi's Sev Khamni. 100% natural 'Heat & Eat' meal since 1942. Includes crispy Sev.",
    descriptionDE: "Authentischer süß-scharfer Geschmack aus Surat. 100% natürlich, seit 1942.",
    price: 3.39,
    unit: '300g (Serving: 2)',
    category: 'ready-to-eat',
    image: PM + 'Khamni Box.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-002',
    name: 'Surati Locho',
    nameDE: 'Surati Locho',
    description: 'Bring the street flavors of Surat to your kitchen. 100% natural ingredients, no preservatives.',
    descriptionDE: 'Straßenküche aus Surat. 100% natürlich, keine Konservierungsstoffe.',
    price: 3.29,
    unit: '500g (Serving: 2)',
    category: 'ready-to-eat',
    image: PM + 'Locho Box.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-003',
    name: 'Vatidal Khaman',
    nameDE: 'Vatidal Khaman',
    description: 'Authentic Gujarati Vatidal Khaman made from stone-ground chana dal. 100% natural.',
    descriptionDE: 'Authentisches gujaratisches Khaman aus steingemahlenem Chana Dal.',
    price: 3.29,
    unit: '500g (Serving: 3)',
    category: 'ready-to-eat',
    image: PM + 'Khaman Box.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-004',
    name: 'Sev Usal',
    nameDE: 'Sev Usal',
    description: 'A spicy street-food classic. Heat & Eat Sev Usal with sprouted beans in a robust gravy.',
    descriptionDE: 'Würziger Straßenküchen-Klassiker. Gekeimte Bohnen in kräftiger Soße.',
    price: 3.29,
    unit: '300g (Serving: 2)',
    category: 'ready-to-eat',
    image: PM + 'Sev Usal Box.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-005',
    name: 'Khavsa',
    nameDE: 'Khavsa',
    description: 'Hearty Rajasthani wheat dish — comfort food at its best.',
    descriptionDE: 'Herzhaftes rajasthanisches Weizengericht — Wohlfühlessen vom Feinsten.',
    price: 3.29,
    unit: '400g (Serving: 2)',
    category: 'ready-to-eat',
    image: PM + 'Khavsa A.jpg',
    inStock: true,
    featured: true,
    brand: 'Raj',
  },
  {
    id: 'CS-006',
    name: 'Misal',
    nameDE: 'Misal',
    description: 'Fiery Maharashtrian Misal in minutes. Sprout-based curry with authentic spices. 100% natural, no MSG.',
    descriptionDE: 'Feuriges maharashtrianisches Misal. Keimbasiertes Curry, 100% natürlich.',
    price: 3.29,
    unit: '300g (Serving: 2)',
    category: 'ready-to-eat',
    image: PM + 'Misal Box.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-037',
    name: 'Dal Chawal',
    nameDE: 'Dal Chawal',
    description: 'Classic yellow dal with fluffy Basmati rice. Freeze-dried, ready in 5 minutes.',
    descriptionDE: 'Klassisches Dal mit Basmati-Reis. Gefriergetrocknet, in 5 Minuten fertig.',
    price: 3.29,
    unit: '400g',
    category: 'ready-to-eat',
    image: PM + 'Dal Chawal.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-038',
    name: 'Dal Khichdi',
    nameDE: 'Dal Khichdi',
    description: 'The ultimate Indian comfort food — a healthy harmony of lentils and rice.',
    descriptionDE: 'Das ultimative indische Wohlfühlessen aus Linsen und Reis.',
    price: 3.29,
    unit: '400g',
    category: 'ready-to-eat',
    image: PM + 'Dal Khichdi.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-039',
    name: 'Dal Makhani',
    nameDE: 'Dal Makhani',
    description: 'Rich creamy slow-cooked black lentils. Freeze-dried, ready in 5 minutes. 100% natural.',
    descriptionDE: 'Reichhaltige cremige schwarze Linsen, langsam gegart. In 5 Minuten fertig.',
    price: 3.29,
    unit: '400g',
    category: 'ready-to-eat',
    image: PM + 'Dal Makhani.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-040',
    name: 'Masala Khichdi Kadhi',
    nameDE: 'Masala Khichdi Kadhi',
    description: 'Spicy vegetable khichdi with tangy yogurt kadhi. Freeze-dried convenience.',
    descriptionDE: 'Würziges Gemüse-Khichdi mit Joghurt-Kadhi.',
    price: 3.29,
    unit: '400g',
    category: 'ready-to-eat',
    image: PM + 'Masala Khichdi Kadhi.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-041',
    name: 'Paneer Butter Masala',
    nameDE: 'Paneer Butter Masala',
    description: 'Tender paneer cubes in a rich butter masala sauce. Ready in 5 minutes.',
    descriptionDE: 'Zarter Paneer in reichhaltiger Butter-Masala-Soße. In 5 Minuten fertig.',
    price: 3.29,
    unit: '400g',
    category: 'ready-to-eat',
    image: PM + 'Paneer Butter Masala.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-042',
    name: 'Paneer Lababdar',
    nameDE: 'Paneer Lababdar',
    description: 'Creamy paneer in a mildly spicy onion-tomato gravy. 100% natural.',
    descriptionDE: 'Cremiger Paneer in milder Zwiebel-Tomaten-Soße. 100% natürlich.',
    price: 3.29,
    unit: '400g',
    category: 'ready-to-eat',
    image: PM + 'Paneer Lababdar.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-043',
    name: 'Paneer Tikka Masala',
    nameDE: 'Paneer Tikka Masala',
    description: 'Grilled paneer in robustly spiced masala gravy. No MSG or artificial colors.',
    descriptionDE: 'Gegrillter Paneer in kräftiger Masala-Soße. Kein MSG oder Farbstoffe.',
    price: 3.29,
    unit: '400g',
    category: 'ready-to-eat',
    image: PM + 'Paneer Tikka Masala_A.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-044',
    name: 'Pav Bhaji',
    nameDE: 'Pav Bhaji',
    description: 'The iconic Mumbai street food — spiced mashed vegetable curry.',
    descriptionDE: 'Das ikonische Mumbaianer Streetfood. Gewürztes Gemüsecurry.',
    price: 3.29,
    unit: '400g',
    category: 'ready-to-eat',
    image: PM + 'Pav Bhaji.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-045',
    name: 'Rajma Masala',
    nameDE: 'Rajma Masala',
    description: 'Slow-cooked red kidney beans in spicy ginger-garlic gravy.',
    descriptionDE: 'Langsam gegarte Kidneybohnen in würziger Ingwer-Knoblauch-Soße.',
    price: 3.29,
    unit: '400g',
    category: 'ready-to-eat',
    image: PM + 'Rajma Masala.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-046',
    name: 'Tava Pulao',
    nameDE: 'Tava Pulao',
    description: 'Spicy vegetable rice cooked Mumbai tava-style. Ready in 5 minutes.',
    descriptionDE: 'Würziger Gemüsereis im Mumbai-Tava-Stil. In 5 Minuten fertig.',
    price: 3.29,
    unit: '400g',
    category: 'ready-to-eat',
    image: PM + 'Tava Pulao.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-047',
    name: 'Veg Biryani',
    nameDE: 'Veg Biryani',
    description: 'Aromatic basmati rice with mountain spices and mixed vegetables. No MSG or preservatives.',
    descriptionDE: 'Aromatischer Basmati-Reis mit Berggewürzen und Gemüse. Kein MSG.',
    price: 3.29,
    unit: '400g',
    category: 'ready-to-eat',
    image: PM + 'Veg Biryani.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-048',
    name: 'Veg Makhanwala',
    nameDE: 'Veg Makhanwala',
    description: 'Garden vegetables in a rich buttery masala sauce.',
    descriptionDE: 'Gartengemüse in reichhaltiger Butter-Masala-Soße.',
    price: 3.29,
    unit: '400g',
    category: 'ready-to-eat',
    image: PM + 'Veg Makhanwala.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },

  // ── NAMKEEN (Patel Markt) ─────────────────────────────────────────────────
  {
    id: 'CS-007',
    name: 'Surti Mix Farshan',
    nameDE: 'Surti Mix Farshan',
    description: 'A crunchy medley of fried snacks from Surat.',
    descriptionDE: 'Eine knusprige Mischung aus gebratenen Snacks aus Surat.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Surati Mix Farsan_Front_A.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-008',
    name: 'Tikha Mix Farshan',
    nameDE: 'Tikha Mix Farshan',
    description: 'Hot and spicy farshan mix for the brave palate.',
    descriptionDE: 'Heiße und würzige Farshan-Mischung für mutige Gaumen.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Tikha Mix_Front_A.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-009',
    name: 'Plain Sev',
    nameDE: 'Plain Sev',
    description: 'Thin crispy gram flour noodles — a classic anytime snack.',
    descriptionDE: 'Dünne knusprige Kichererbsenmehl-Nudeln — ein klassischer Snack.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Plain Sev_Front_A.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-010',
    name: 'Nylon Sev (Zero Size)',
    nameDE: 'Nylon Sev (Zero Size)',
    description: 'Ultra-fine sev perfect for bhel and chaat toppings.',
    descriptionDE: 'Ultrafeine Sev — perfekt für Bhel und Chaat.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Nylon Sve_Front_A.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-011',
    name: 'Tikha Gathiya',
    nameDE: 'Tikha Gathiya',
    description: 'Spicy thick gram flour sticks — a Gujarati tea-time favourite.',
    descriptionDE: 'Würzige Kichererbsenmehl-Sticks — gujaratischer Tee-Klassiker.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Tikha Gathiya_Front_A.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-012',
    name: 'Plain Gathiya',
    nameDE: 'Plain Gathiya',
    description: 'Classic unsalted gathiya — light and crunchy.',
    descriptionDE: 'Klassische ungesalzene Gathiya — leicht und knusprig.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Plain Gathiya_Front_A.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-050',
    name: 'Papdi',
    nameDE: 'Papdi',
    description: 'Crispy flat wafers perfect for chaat and snacking.',
    descriptionDE: 'Knusprige flache Wafern — ideal für Chaat.',
    price: 2.99,
    unit: '200g',
    category: 'namkeen',
    image: PM + 'Papdi_Front_A.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-051',
    name: 'Poha Chevdo',
    nameDE: 'Poha Chevdo',
    description: 'Lightly spiced flattened rice mix with nuts and raisins.',
    descriptionDE: 'Leicht gewürzter Reisflocken-Mix mit Nüssen und Rosinen.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Poha Chevdo_Front_A.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-015',
    name: 'Makkai Chevdo',
    nameDE: 'Makkai Chevdo',
    description: 'Crunchy corn flakes chevdo with Indian spices.',
    descriptionDE: 'Knuspriger Maisflocken-Chevdo mit indischen Gewürzen.',
    price: 3.49,
    unit: '200g',
    category: 'namkeen',
    image: PM + 'Makkai Chevda_Front_A.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-016',
    name: 'Channa Dal Snack',
    nameDE: 'Channa Dal Snack',
    description: 'Roasted split chickpea snack — high in protein.',
    descriptionDE: 'Gerösteter Kichererbsen-Snack — proteinreich.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Chana Dal_Front_A.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-017',
    name: 'Bhel Mix with Puri',
    nameDE: 'Bhel Mix mit Puri',
    description: 'All-in-one bhel mix kit with puris included.',
    descriptionDE: 'Komplettes Bhel-Mix-Set mit Puris.',
    price: 3.99,
    unit: '500g',
    category: 'namkeen',
    image: PM + 'Bhel_Aa.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-018',
    name: 'Kolhapuri Bhadang Bhel',
    nameDE: 'Kolhapuri Bhadang Bhel',
    description: 'Spicy puffed rice snack from Maharashtra.',
    descriptionDE: 'Würziger gepuffter Reis-Snack aus Maharashtra.',
    price: 3.99,
    unit: '500g',
    category: 'namkeen',
    image: PM + 'Kolhapuri Bhel Mix_Front_A.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-019',
    name: 'Lemon Bhel',
    nameDE: 'Lemon Bhel',
    description: 'Tangy lemon-flavoured puffed rice mix.',
    descriptionDE: 'Säuerlicher Zitronen-Puffreis-Mix.',
    price: 3.99,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Lemon Mix_Front_A.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-020',
    name: 'Dry Fruit Farali Chevdo',
    nameDE: 'Dry Fruit Farali Chevdo',
    description: 'Premium fasting chevdo loaded with dry fruits.',
    descriptionDE: 'Premium-Fasten-Chevdo mit getrockneten Früchten.',
    price: 3.99,
    unit: '500g',
    category: 'namkeen',
    image: PM + 'Falahari Chivda_Front_A.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },
  {
    id: 'CS-021',
    name: 'Tikhi Sev',
    nameDE: 'Tikhi Sev',
    description: 'Spicy thin sev with a fiery kick.',
    descriptionDE: 'Würzige dünne Sev mit feurigem Kick.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Tikhi Sev_Front_A.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-022',
    name: 'Limbu Mari Sev',
    nameDE: 'Limbu Mari Sev',
    description: 'Tangy lemon pepper sev — refreshingly zesty.',
    descriptionDE: 'Säuerliche Zitronen-Pfeffer-Sev — erfrischend würzig.',
    price: 3.99,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Limboo Mari Sev_Front_A.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-023',
    name: 'Golden Chevdo',
    nameDE: 'Golden Chevdo',
    description: 'Sweet and savoury golden chevdo with cashews.',
    descriptionDE: 'Süß-salziger goldener Chevdo mit Cashews.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Golden Chevdo.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-024',
    name: 'Kashmiri Chevdo',
    nameDE: 'Kashmiri Chevdo',
    description: 'Rich and aromatic chevdo with Kashmiri spices.',
    descriptionDE: 'Reichhaltiger Chevdo mit Kashmiri-Gewürzen.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Kashmiri Chevdo.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-025',
    name: 'Pudina Sev',
    nameDE: 'Pudina Sev',
    description: 'Mint-flavoured sev — cool and crunchy.',
    descriptionDE: 'Minz-Sev — kühl und knusprig.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Pudina Sev.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-026',
    name: 'Aloo Sev',
    nameDE: 'Aloo Sev',
    description: 'Potato-based thin sev — a crispy delight.',
    descriptionDE: 'Dünne kartoffelbasierte Sev — ein knuspriger Genuss.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Aloo Sev.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-027',
    name: 'Bhathakani',
    nameDE: 'Bhathakani',
    description: 'Traditional Gujarati biscuit snack.',
    descriptionDE: 'Traditioneller gujaratischer Keks-Snack.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Bhatha Kani.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-028',
    name: 'Punjabi Mix',
    nameDE: 'Punjabi Mix',
    description: 'Bold spiced mix inspired by North Indian flavours.',
    descriptionDE: 'Kräftige Gewürzmischung nach nordindischer Art.',
    price: 3.49,
    unit: '500g',
    category: 'namkeen',
    image: PM + 'Punjabi Mix.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-029',
    name: 'Fruyms Chevdo',
    nameDE: 'Fruyms Chevdo',
    description: 'Colourful fruyms mixed with spicy chevdo.',
    descriptionDE: 'Bunte Fruyms mit würzigem Chevdo gemischt.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Fryums Chevdo.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-030',
    name: 'Sp. Lasan Mix Chevdo',
    nameDE: 'Sp. Lasan Mix Chevdo',
    description: 'Garlic-flavoured chevdo — aromatic and addictive.',
    descriptionDE: 'Knoblauch-Chevdo — aromatisch und unwiderstehlich.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Sp. Lasan Mix Chevdo.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-031',
    name: 'Nylon Chevdo',
    nameDE: 'Nylon Chevdo',
    description: 'Fine nylon sev tossed with spiced chevdo mix.',
    descriptionDE: 'Feine Nylon-Sev mit gewürzter Chevdo-Mischung.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Nylon Chevdo.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-032',
    name: 'Aloo Chat Mix',
    nameDE: 'Aloo Chat Mix',
    description: 'Ready-to-eat aloo chaat snack mix.',
    descriptionDE: 'Verzehrfertiger Aloo-Chaat-Snack-Mix.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Aloo Chat Mix.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-033',
    name: 'Lilu Lasan Bhel Mix',
    nameDE: 'Lilu Lasan Bhel Mix',
    description: 'Green garlic flavoured bhel mix — seasonal favourite.',
    descriptionDE: 'Grüner Knoblauch Bhel Mix — saisonaler Favorit.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Lilu Lasan Mix.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-034',
    name: 'Wheat Chevdo',
    nameDE: 'Wheat Chevdo',
    description: 'Crunchy wheat flakes chevdo — wholesome and tasty.',
    descriptionDE: 'Knusprige Weizenflocken-Chevdo — gesund und lecker.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Wheat Chevdo.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-035',
    name: 'Ful Jadi',
    nameDE: 'Ful Jadi',
    description: 'Traditional puffed snack with a unique texture.',
    descriptionDE: 'Traditioneller gepuffter Snack mit einzigartiger Textur.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Fuljadi.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-036',
    name: 'Tal Katri',
    nameDE: 'Tal Katri',
    description: 'Crispy sesame wafers — a delicate savoury treat.',
    descriptionDE: 'Knusprige Sesamwafern — ein delikater herzhafter Genuss.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Tal Katri.png',
    inStock: true,
    featured: false,
    brand: 'Madhi',
  },
  {
    id: 'CS-049',
    name: 'Tikho Farali Chevdo',
    nameDE: 'Tikho Farali Chevdo',
    description: 'Spicy fried potato sticks for fasting occasions.',
    descriptionDE: 'Würzige gebratene Kartoffelsticks für Fastentage.',
    price: 3.49,
    unit: '400g',
    category: 'namkeen',
    image: PM + 'Tikho Farali Chevdo.png',
    inStock: true,
    featured: true,
    brand: 'Madhi',
  },

  // ── FRUITS & VEGGIES (Patel Markt) ───────────────────────────────────────
  {
    id: 'CS-013',
    name: 'Alphonso Mango Box',
    nameDE: 'Alphonso Mango Box',
    description: 'Premium quality Alphonso Mangoes imported directly from India.',
    descriptionDE: 'Premium Alphonso Mangos direkt aus Indien importiert.',
    price: 18.99,
    unit: 'approx. 1.5 kg',
    category: 'fruits-veggies',
    image: PM + 'Alphonso_Mango.png',
    inStock: true,
    featured: true,
    brand: 'Alphonso',
  },
  {
    id: 'CS-014',
    name: 'Kesar Mango Box',
    nameDE: 'Kesar Mango Box',
    description: 'Sweet and vibrant Kesar Mangoes sourced directly from Gujarat farms.',
    descriptionDE: 'Süße Kesar-Mangos direkt von Gujarat-Farmen.',
    price: 19.99,
    unit: 'approx. 1.5 kg',
    category: 'fruits-veggies',
    image: PM + 'Kesar_Mango.png',
    inStock: true,
    featured: true,
    brand: 'Kesar',
  },

  // ── OILS & GHEE ───────────────────────────────────────────────────────────
  {
    id: 'p37',
    name: 'Pure Desi Ghee',
    nameDE: 'Reines Desi Ghee',
    description: 'Traditionally prepared clarified butter with a rich, nutty aroma.',
    descriptionDE: 'Traditionell hergestellte geklärte Butter mit reichem, nussigem Aroma.',
    price: 10.49,
    unit: '500 g',
    category: 'oils',
    image: J + 'Mothers-Kitchen-500g-Reines-Ghee-9040436_1.png',
    inStock: true,
    featured: true,
    brand: "Mother's Kitchen",
  },
  {
    id: 'p38',
    name: 'Pure Butter Ghee',
    nameDE: 'Reines Butter Ghee',
    description: 'High-quality clarified butter for cooking, frying, and traditional sweets.',
    descriptionDE: 'Hochwertiges geklärtes Butterschmalz zum Kochen, Braten und für Süßspeisen.',
    price: 10.19,
    unit: '500 g',
    category: 'oils',
    image: J + 'TRS-500g-Reines-Butter-Ghee-9017219_1.png',
    inStock: true,
    featured: false,
    brand: 'TRS',
  },
  {
    id: 'p39',
    name: 'Coconut Oil',
    nameDE: 'Kokosöl',
    description: 'Pure coconut oil with a delicate tropical flavour, ideal for South Indian cooking.',
    descriptionDE: 'Reines Kokosöl mit zartem Tropenaroma – ideal für südindische Küche.',
    price: 5.59,
    unit: '500 ml',
    category: 'oils',
    image: 'https://www.jamoona.com/cdn/shop/files/Anjappar-1l-Kokosnussoel-9017849_253be8c6-e27a-4ca1-b96a-c766b5bf886e.png?v=1753221285&width=500',
    inStock: true,
    featured: false,
    brand: 'Anjappar',
  },
  {
    id: 'p40',
    name: 'Mustard Oil',
    nameDE: 'Senföl',
    description: 'Pungent, flavourful mustard oil – essential in Bengali and North Indian cooking.',
    descriptionDE: 'Würziges Senföl – unverzichtbar in der bengalischen und nordindischen Küche.',
    price: 3.79,
    unit: '1 L',
    category: 'oils',
    image: J + 'Schani-1l-Senfoel-9039554_c699e023-59af-4a3a-b87d-3b4423dc802d.png',
    inStock: true,
    featured: false,
    brand: 'Schani',
  },
];

export const categories: Category[] = [
  'spices',
  'lentils',
  'rice',
  'flour',
  'snacks',
  'beverages',
  'pickles',
  'oils',
  'ready-to-eat',
  'namkeen',
  'fruits-veggies',
];

export const categoryEmoji: Record<Category, string> = {
  spices: '🌶️',
  lentils: '🫘',
  rice: '🍚',
  flour: '🌾',
  snacks: '🍿',
  beverages: '🥤',
  pickles: '🥭',
  oils: '🫙',
  'ready-to-eat': '🍱',
  namkeen: '🥨',
  'fruits-veggies': '🥭',
};

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getProductsByCategory(category: Category): Product[] {
  return products.filter((p) => p.category === category);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
